# This is a basic workflow to help you get started with Actions

name: NuGet

# Controls when the workflow will run
on:
  # Triggers the workflow on push to main
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive # for the proto files
          fetch-depth: 0 # For GitVersion

      # Setup GitVersion
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'
      - name: Execute GitVersion
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true
        
      - name: Build
        run: dotnet build

      - name: Pack
        run: dotnet pack -p:PackageVersion=${{ steps.version_step.outputs.GitVersion_MajorMinorPatch }}

      - name: Push
        run: dotnet nuget push "**/*.${{ steps.version_step.outputs.GitVersion_MajorMinorPatch }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
